ANYAnyGlobToAnyFile:
- changed-files: 
  - any-glob-to-any-file: ['*.js', '**']
  - any-glob-to-all-files: ['*.js']
  - all-globs-to-any-file: ['*.js']
  - all-globs-to-all-files: '*.js'

ANYAnyGlobToAllFiles:
- any:
  - changed-files: 
    - any-glob-to-any-file: ['*.js']
    - any-glob-to-all-files: ['*.js', '**']
    - all-globs-to-any-file: '*.js'
    - all-globs-to-all-files: ['*.js']

ANYAllGlobsToAnyFile:
- changed-files: 
  - any-glob-to-any-file: '*.js'
  - any-glob-to-all-files: ['*.js']
  - all-globs-to-any-file: ['**', '**']
  - all-globs-to-all-files: ['*.js']

ANYAllGlobsToAllFiles:
- any:
  - changed-files: 
    - any-glob-to-any-file: ['*.js']
    - any-glob-to-all-files: ['*.js']
    - all-globs-to-any-file: ['*.js']
    - all-globs-to-all-files: ['**', '**']

ANYNoMatch:
- any:
  - changed-files: 
    - any-glob-to-any-file: ['*.js']
    - any-glob-to-all-files: ['*.js']
    - all-globs-to-any-file: ['*.js']
    - all-globs-to-all-files: ['*.js']

ANYOneObject:
- any:
  - changed-files: 
    - any-glob-to-any-file: ['*.js']
      any-glob-to-all-files: ['*.js']
      all-globs-to-any-file: ['*.js']
      all-globs-to-all-files: ['**']

ALLNoMatch:
- all:
  - changed-files: 
    - any-glob-to-any-file: ['**']
    - any-glob-to-all-files: ['**']
    - all-globs-to-any-file: ['**']
    - all-globs-to-all-files: ['*.js']

ALLMatched:
- all:
  - changed-files: 
    - any-glob-to-any-file: '**'
    - any-glob-to-all-files: ['**']
    - all-globs-to-any-file: ['**']
    - all-globs-to-all-files: ['**']

ALLOneObject:
- all:
  - changed-files: 
    - any-glob-to-any-file: ['**']
      any-glob-to-all-files: ['**']
      all-globs-to-any-file: ['**']
      all-globs-to-all-files: ['**']

ANYandALLCFMatched:
- any:
  - changed-files: 
    - all-globs-to-all-files: ['**']
- all:
  - changed-files: 
    - any-glob-to-any-file: ['**']

ANYandALLCFNoMatch:
- any:
  - changed-files: 
    - all-globs-to-all-files: ['**']
- all:
  - changed-files: 
    - any-glob-to-any-file: ['**']
    - all-globs-to-all-files: ['*.js']

ANYandALLCFAndBranchNoMatch:
- any:
  - base-branch: ['main']
  - changed-files: 
    - all-globs-to-all-files: ['**']
- all:
  - changed-files: 
    - any-glob-to-any-file: ['**']
    - all-globs-to-all-files: ['*.js']

ANYandALLCFAndBranchMatched:
- any:
  - base-branch: ['main']
  - changed-files: 
    - all-globs-to-all-files: ['**']
- all:
  - head-branch: ['new']
  - changed-files: 
    - any-glob-to-any-file: ['**']
    - all-globs-to-all-files: ['**']

