name: Test the original action
on:
  - pull_request_target

jobs:
  job1:
    name: Simple string
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5.0.0
        with:
          configuration-path: .github/config-issue.yml
