name: "dot"
on:
- pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: maksimzhukov/labeler@resolve-merge-conflicts
    
    - uses: maksimzhukov/labeler@resolve-merge-conflicts
      with: 
        dot: true
