name: "Manual testing"
on:
  workflow_dispatch:
    inputs:
      PR_NUMBER:
        description: 'PR number'
        required: true

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: maksimzhukov/labeler@resolve-merge-conflicts
      with:       
        configuration-path: '.github/labels-limit.yml'
        pr-number: |
          ${{ inputs.PR_NUMBER }}
