name: "Sync"
on:
- pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:      
    - name: Labeler
      uses: actions/labeler@v4.0.2
      with:       
        configuration-path: '.github/labelerOld.yml'

